/* DO NOT EDIT THIS FILE - it is machine generated */
#include </Users/erik/bin/android-ndk-r9c/platforms/android-19/arch-arm/usr/include/jni.h>
/* Header for class com_self_ishowproj_Logic */

#ifndef _Included_com_self_ishowproj_Logic
#define _Included_com_self_ishowproj_Logic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_self_ishowproj_Logic
 * Method:    trigger
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_self_ishowproj_Logic_trigger
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
